# Config file for automatic testing at travis-ci.org

language: python
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

install: pip install -U tox-travis flake8

# Command to run tests, e.g. python setup.py test
script:
  - flake8 .
  - tox

# Assuming you have installed the travis-ci CLI tool, after you
# create the Github repo and add it to Travis, run the
# following command to finish PyPI deployment setup:
# $ travis encrypt --add deploy.password
# TODO
# deploy:
#   provider: pypi
#   distributions: sdist bdist_wheel
#   user: mdboom
#   password:
#     secure: PLEASE_REPLACE_ME
#   on:
#     tags: true
#     repo: mdboom/glean_parser
#     python: 3.7
