env:
  matrix:
    secure: mv2yxS8voomllIlMBRHs2yZV9vULT3LTuzSgKEDh9nld5lKAiMnl0pwWIumc/v8+DJb07a1Upc91ksLDkbqhuIcdbu6iqzhGQTtQTLNNYm0mj1ww/99Cs2sZKwA1LNjzQdQ/26FxAru5bDOp8k/l6DtwyUMVd42X2lwdfeMqq/snYXP+BDZ/0gzeUYB+DVzIvT/dv04+qoM8Plm4vgjxSDMXUzoynInomh9g331PiGieQsAOi9Cz6f35FJPvr8DjEKPs86XTnsN+cnv1WUZn87I0jsEzyE9CMGc12b28/RJNMJH+918/seLkacqvkkGDdzgnktRfGJQAo7Y4MmN8YGsivhD3ckRlAK0vReEQar4HKjtS/iED0JhyIH99PTPYtV40SjY0mBhYvAnrpKkwCUvUO57DhfHFBBlIbrfCOlM0099RVVeGj8UeKI20s1Bwpq7OeeSvew4N6wRCnI25W5rVwkDXBOOB7svpO4IITITDxUYSGCButbZXvPvl8vEJXHFY4qh9etDMLKzbQJsBnqPnIqnEUDxIFXUC06XPBgFONY4vqYYZ2S9LZ+t34jKP/YWQ7nVuN8o199gYgLX0SQXgAgW1hXeBO6wfWBGdbLO72hdErZLjEEOlc5qnc6QiD+hUWnd/VRHtfZoLjr1M1QgpWnZdR5rblr/2H13j2G0=
language: python
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
install:
  - pip install -U tox-travis flake8
  - curl -sSLO https://github.com/shyiko/ktlint/releases/download/0.29.0/ktlint && chmod a+x ktlint
script:
  - export PATH=.:$PATH
  - flake8 .
  - tox
  - pip install -r requirements_dev.txt
  - python setup.py develop
  - make docs
deploy:
  - provider: pypi
    distributions: sdist bdist_wheel
    user: mdboom2
    password:
      secure: UX0nwEz6fhe5PwT4ptrCfLpfWWeqHYHXelQgUZnvpSvYmnaVOGlDsgAYIalezRatqOHUx1UP7zCvQ+IbULn2hMocRKfE7CMvaKHbXYUiSBdAB8H86YcVFXoIshL/nLMypoANsIKljE2bv5FF5E3ru9mOo2UjPp9kC1hgFNuLo9ZWHZzuarsC6CAGtD1BnSyQa7ove0NP3pMe23Fe41OSYXJTSMXNXj9d3PT4WfsMBOYYvEA7WH4Eax5JtZcAMFhSnkCN0wdanVdStRrdyOrgc12AgbbVFvpEIrteahcNOJC7BJDm86JI1kKo+PZ//wf3fi+lZAvrg3wVXlvaJQ8xqwOidGAMdMqFuo+L/3Xyn6whkcFU7tQsXBVsF4GoL8EiKoDRNZ1rJu1AJvhyyq6mBvp142l1xSQrDwzbuqAlSSJH9Z4mDneSLf+AUDFiSDwwW/oYbOwm8pEvZUFZdAKEt2Rdt6LVn5+Ao7KV8F5YSvfHbyr9MfLsuO6zzjUxxm+nw1gdLnE1vN94veahCHb4n+oBwviLmtzYTrA967vgC9PPChGxCgrPhCqbCIwe1Xa+ivYqFu8LsIW19Sg2dqp1P9NyXTCWM3NPSakt6QyMWw9qS7zAt4yGt/rKLM46P7Ad1t+UKR9EqX84KL+z9WzG1gkForTmZYxCo6b9YIlcuDw=
    on:
      tags: true
      repo: mozilla/glean_parser
      python: 3.7
  - provider: pages
    skip-cleanup: true
    keep-history: false
    github-token: "$GITHUB_TOKEN"
    local-dir: docs/_build/html
    target-branch: gh-pages
    on:
      tags: true
